apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dmsw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dmsw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0068-app
  name: devfile-sample-dmsw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dmsw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dmsw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-dmsw@sha256:21df507935b20152a9cb8875a3a69ca016eeb89242499591e93de00cab96820c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
